# Generated by Django 6.1.1 on 2026-10-08 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_from_validations(apps, schema_editor):
    """Seed history from reviews that still exist. Reviews already wiped by
    earlier resubmits can't be recovered."""
    Validation = apps.get_model('core', 'Validation')
    ReviewLog = apps.get_model('core', 'ReviewLog')
    ReviewLog.objects.bulk_create([
        ReviewLog(
            assignment_id=v.solution.assignment_id,
            question_id=v.solution.question_id,
            solution_id=v.solution_id,
            solver_id=v.solution.solver_id,
            reviewer_id=v.reviewer_id,
            is_working=v.is_working,
            comment=v.comment,
            reviewed_at=v.reviewed_at,
        )
        for v in Validation.objects.select_related('solution')
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resubmitnotice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.question')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_logs', to='core.solution')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reviewed_at', '-id'),
                'indexes': [models.Index(fields=['assignment', 'reviewer'], name='core_review_assignm_bdbeb7_idx')],
            },
        ),
        migrations.RunPython(backfill_from_validations, migrations.RunPython.noop),
    ]
