# Generated by Django 6.1.1 on 2026-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("participant", "Participant"),
                    ("course_team", "Course Team"),
                ],
                default="participant",
                max_length=20,
            ),
        ),
    ]
